CREATE TABLE events (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
	title varchar(20) NOT NULL,
	description varchar(5000),
	category varchar(20) NOT NULL,
	location varchar(30) NOT NULL,
	capacity int NOT NULL,
	event_date TIMESTAMP NOT NULL,
	creation_date TIMESTAMP NOT NULL,
	duration int NOT NULL,
	creator varchar(10) NOT NULL,
	PRIMARY KEY (id)
);

CREATE TABLE users (
	login varchar(10) NOT NULL,
	password varchar(64) NOT NULL,
	role varchar(10) NOT NULL,
	PRIMARY KEY (login)
);

CREATE TABLE assistants (
	id_event int NOT NULL,
	id_user varchar(10) NOT NULL,
	PRIMARY KEY (id_event, id_user)
);
